- name: Create Azure VM
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: sertacansible
      location: eastus

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: sertacansible
      name: sertacVnet
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: sertacansible
      name: sertacSubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: sertacVnet

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: sertacansible
      allocation_method: Static
      name: sertacPublicIP

  # - name: Create a load balancer
  #   azure_rm_loadbalancer:
  #     name: sertacloadbalancer
  #     resource_group: sertacansible
  #     public_ip: sertacansible
  #     probe_protocol: Tcp
  #     probe_port: 80
  #     probe_interval: 10
  #     probe_fail_count: 3
  #     protocol: Tcp
  #     load_distribution: Default
  #     frontend_port: 80
  #     backend_port: 8080
  #     idle_timeout: 4
  #     natpool_frontend_port_start: 1030
  #     natpool_frontend_port_end: 1040
  #     natpool_backend_port: 80
  #     natpool_protocol: Tcp

  # - name: Create Network Security Group that allows SSH
  #   azure_rm_securitygroup:
  #     resource_group: sertacansible
  #     name: sertacNetworkSecurityGroup
  #     rules:
  #       - name: SSH
  #         protocol: Tcp
  #         destination_port_range: 22
  #         access: Allow
  #         priority: 1001
  #         direction: Inbound

  # - name: Create virtual network interface card
  #   azure_rm_networkinterface:
  #     resource_group: sertacansible
  #     name: sertacNIC
  #     virtual_network: sertacVnet
  #     subnet: sertacSubnet
  #     public_ip_name: sertacPublicIP
  #     # security_group: sertacNetworkSecurityGroup
  #     # load_balancer: sertacloadbalancer

  - name: get ssh key
    command: cat ~/.ssh/id_rsa.pub
    register: sshkey

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: sertacansible
      name: sertacVM
      vm_size: Standard_DS1_v2
      admin_username: sozercan
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/sozercan/.ssh/authorized_keys
          key_data: '{{ sshkey.stdout }}'
      network_interfaces: sertacNIC
      # storage_account: sertacosstorage
      # storage_container: osdisk
      # storage_blob: osdisk.vhd
      managed_disk_type: Standard_LRS
      image:
        offer: CoreOS
        publisher: CoreOS
        sku: Stable
        version: latest
      data_disks:
        - lun: 0
          disk_size_gb: 64
          managed_disk_type: Standard_LRS
      # data_disk_lun: 0
      # data_disk_storage_account: sertacdatastorage
      # data_disk_storage_container: datadisk2
      # data_disk_storage_blob: datadisk2.vhd
      # data_disk_size_gb: 64
      # data_disk_managed_disk_type: Standard_LRS

  # - name: Create VM Extension
  #   azure_rm_virtualmachine_extension:
  #     resource_group: sertacansible
  #     name: sertacVMExtension
  #     virtual_machine_name: sertacVM
  #     publisher: Microsoft.Azure.Extensions
  #     virtual_machine_extension_type: CustomScript
  #     type_handler_version: 2.0
  #     auto_upgrade_minor_version: true
  #     settings: {"commandToExecute": "hostname"}

